### ISSUE TITLE
Hold user test with service owners

### ISSUE THREAD

**Issue by sorensensig** [Altinn/altinn-resource-registry#172]
### Description

As we move further towards understanding the metadata in the resource registry and policy, we need to meet with service owners to test this design and gather valuable feedback around their user flows and needs. This includes for setting up the resource and policy. Usability questions from [UMUX-lite](https://measuringu.com/umux-lite-useful-alternative/) (perceived ease of use and perceived usability) will be asked in addition to the addressing the main goal of understanding 1) migration, 2) form fields and understandability, 3) user flow and functionality. 

Our approach is also heavily inspired by[ GOV.UK ](https://userresearch.blog.gov.uk/2019/09/13/how-a-spreadsheet-can-make-usability-analysis-faster-and-easier/)when it comes to both the spreadsheet rainbow layout (quickly scanning red for no and green for yes) and the 'data suggests - so if we try - and measure- we should see this change' model.

### Additional Information

- [x] Organise the questions and design we want to test with participants
- [x] Reach out to service owners that have both in app and lenketjenester
- [ ] Hold 3 conceptual user testing sessions
- [ ] Analyse data
- [ ] Report back to our team

Definition of success:

1. Establish the _minimum fields required _ from service owners
2. Flag any issues with content and descriptions for filling out fields
3. Find any top-level usability issues to fix
4. Successful handover to developers for quick implementation of the MVP

- [ ] This will need to be followed by WCAG/UU testing

Example below of testing spreadsheet template
![Screenshot 2023-05-26 at 11 51 17](https://github.com/Altinn/altinn-resource-registry/assets/19344884/4fbb9d1d-aa7b-4cf3-951c-5a3a8f4a3468)

**Comment by indiamaydesign** [comment]
@sorensensig and I met with with Brønnøysundregistrene two weeks ago. Outcomes:

- Great enthusiasm for CPSV as a standard and idea of resource registry
- Consider organisational form instead of organisational type
- Confusion around terms that clash with their own terminology i.e. 1) the terms resource and policy, 2) joint services and life events as the term event is associated with incidents and 3) rule sets were another problematic term. These terms were all considered a bit technical.
